import { VERTICAL_PLANTAS } from './VERTICAL_PLANTAS'
import { VERTICAL_SERVICIOS } from './VERTICAL_SERVICIOS'
import { VERTICAL_VIVERO } from './VERTICAL_VIVERO'
import { HORIZONTAL_PLANTAS } from './HORIZONTAL_PLANTAS'
import { HORIZONTAL_VIVERO } from './HORIZONTAL_VIVERO'
import { HORIZONTAL_SERVICIO } from './HORIZONTAL_SERVICIOS'

export {
    VERTICAL_PLANTAS,
    VERTICAL_SERVICIOS,
    VERTICAL_VIVERO,
    HORIZONTAL_PLANTAS,
    HORIZONTAL_VIVERO,
    HORIZONTAL_SERVICIO
}